export { default as Blog } from './blog/Blog'
export { default as Features } from './features/features'
export { default as Footer } from './footer/footer'
export { default as Header } from './header/header'
export { default as Possibility } from './possibility/Possibility'
export { default as WHATGPT3 } from './whatGPT3/WHATGPT3'
